name: APKBUILD Package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build APK package in Alpine
        uses: addnab/docker-run-action@v3
        with:
          image: alpine:edge
          options: -v ${{ github.workspace }}:/workspace
          run: |
            apk update
            apk add alpine-sdk build-base fakeroot sudo
            adduser -D builder
            echo "builder ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
            addgroup builder abuild
            mkdir -p /var/cache/distfiles
            chown builder:abuild /var/cache/distfiles
            chown -R builder:abuild /workspace
            
            su builder -c "
              cd /workspace
              export PACKAGER='GitHub Actions <github@actions>'
              abuild-keygen -a -i -n
              abuild checksum
              abuild -r
            "
            
            # 复制生成的 apk 到工作目录
            find /home/builder/packages -name '*.apk' -exec cp {} /workspace/ \;

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: apk-packages
          path: |
            ./*.apk
            ./src/*.apk
