name: APKBUILD Package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build APK package in Alpine
        uses: addnab/docker-run-action@v3
        with:
          image: alpine:latest
          options: -v ${{ github.workspace }}:/workspace
          run: |
            apk update
            apk add alpine-sdk fakeroot shadow
            adduser -D builder
            echo "builder ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
            chown -R builder:builder /workspace
            su builder -c "
              cd /workspace
              export PACKAGER='github@actions'
              export PACKAGER_PRIVKEY=/workspace/abuild.key
              abuild-keygen -a -n -i
              abuild -r
            "
            # 查找所有生成的 .apk 文件
            find /workspace -name '*.apk' -exec cp {} /workspace/ \;

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: apk-packages
          path: ./*.apk
